name: Java Maven Build & Deploy

on:
  push:
    branches: [ "master", "develop","feature-createchange","createco" ]
  pull_request:
    branches: [ "master", "develop", "feature-createchange","createco" ]

jobs:

  createco:
    name: ServiceNow create change
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow Change create
        uses: ServiceNow/servicenow-devops-change@v3.0.0
        with:
          
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'createco'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '120'
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: true
          
  deploy:
     name: Deploy
     needs: createco
     runs-on: ubuntu-latest

     steps:
        - name: Run deployment script
          run: echo "Deployment finished"
      

          
