name: workflowToken


on:
  push:
    branches: [ "master", "develop", "feature-testchange" ]
  pull_request:
    branches: [ "master", "develop"]
    
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: create a change 
      run: |
       curl "https://dev127764.service-now.com/api/sn_chg_rest/v1/change" --request POST --header "Accept:application/json" --header "Content-Type:application/json" \
       --data "{
       \"chg_model\" : \"Standard\",
       \"description\" : \"Describes the change request.\",
       \"short_description\" : \"My change request\",
       \"type\" : \"Standard\"
       }" \
       --user "${{ secrets.SNOW_USERNAME }}":"${{ secrets.SNOW_PASSWORD }}"
