name: JAVA-SNOW-CICD-POC


on:
  push:
    branches: [ "master", "develop","feature-testgithash" ]
  pull_request:
    branches: [ "master", "develop", "feature-testgithash"]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml  
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mvn test
    - run: mkdir staging && cp target/*.jar staging && cp target/surefire-reports/*.xml staging && cp target/surefire-reports/TEST-hello.GreeterTest.xml target/surefire-reports/testng-results.xml
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
    - name: Declare some variables
      shell: bash
      run: |
       echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
       echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
    - name: Another step
      run: |
       echo "Branch: ${{ env.branch }}"
       echo "Sha: ${{ env.sha_short }}"
  registerartifact:
     needs: publish-job
     runs-on: ubuntu-latest
     name: ServiceNow Register Artifact
   
     steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Declare some variables
        shell: bash
        run: |
         echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
         echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
      - name: Extract Version
        run: |
          versions=$(grep -oP '<version>\K[^<]+' pom.xml)
          echo " Version extrated from pom.xml: $version"
          
        
      - name: ServiceNow Register Artifact
        uses: ServiceNow/servicenow-devops-register-artifact@v2.0.0
        id: update
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Register Artifact'
          artifacts: '[{"name": "org.springframeworkra","version": "${{ env.sha_short }}_${{ env.branch }}","semanticVersion": "${{ env.sha_short }}","repositoryName": "${{ github.repository }}"}]'
  registerpackage:
     needs: registerartifact
     runs-on: ubuntu-latest
     name: ServiceNow Register Package

     steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ServiceNow Register Package
        uses: ServiceNow/servicenow-devops-register-package@v2.0.0
        id: update
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Register Package'
          artifacts: '[{"name": "org.springframeworkrp","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'
          package-name: 'gs-maven-0.1.0.jar'
