name: workflowToken

on:
  push:
    branches: [ "snowco-test" ]
  pull_request:
    branches: [ "snowco-test" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 17
      
      - name: Maven Build
        run: mvn clean install
        
      - name: Run JUnit Tests
        run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
        
  publish-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mvn test
      - run: mkdir staging && cp target/*.jar staging && cp target/surefire-reports/*.xml staging && cp target/surefire-reports/TEST-hello.GreeterTest.xml target/surefire-reports/testng-results.xml && ls -l staging/ && ls -l target/surefire-reports/ 
      - uses: actions/upload-artifact@v3
        with:
           name: Package
           path: staging

      - name: ServiceNow Test Action Report
        uses: ServiceNow/servicenow-devops-test-report@v3.0.0
      - name: get Xml details
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'publish-job'
          xml-report-filename: staging/TEST-hello.GreeterTest.xml
          
